import Head from "next/head";
import { useState } from "react";
import { BsFillSendFill } from "react-icons/bs";


export default function Home() {
  const [response, setResponse] = useState("");
  const [message, setMessage] = useState("");
  const [pending, setPending] = useState(null);

  const handleChange = (e) => {
    setMessage(e.target.value);
  };

  const handleClick = async () => {
    setPending(true);
    try {
      let response = await fetch("/api/gpt", {
        method: "POST",
        headers: {
          "Content-Type": "applications/json",
        },
        body: JSON.stringify(message),
      });
      let data = await response.json();
      setResponse(data);
      setPending(false);
      setMessage("");
    } catch (error) {
      console.log(error.messsage);
    }
  };
  return (
    <div className="flex flex-col min-h-screen bg-gray-400">
      <Head>
        <title>CHAT GPT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex-1 flex items-center justify-center">
        <div className="max-w-screen-lg mx-auto text-center text-4xl pb-24">
          {pending && (
            <div class="flex items-center justify-center">
              <div
                class="inline-block h-8 w-8 animate-spin rounded-full border-4 border-solid border-current border-r-transparent align-[-0.125em] motion-reduce:animate-[spin_1.5s_linear_infinite]"
                role="status"
              >
                <span class="!absolute !-m-px !h-px !w-px !overflow-hidden !whitespace-nowrap !border-0 !p-0 ![clip:rect(0,0,0,0)]">
                  Loading...
                </span>
              </div>
            </div>
          )}
          {response}
          
        </div>
      </div>
      <div className="fixed bottom-0 bg-gray-500 p-4 w-full">
        <div className="max-w-screen-lg mx-auto flex gap-2">
          <input
            type="text"
            className="flex-1 p-4 rounded"
            value={message}
            onChange={handleChange}
            placeholder="what do you want to know ?😁"
          />
          <button
            className="py-4 px-6 bg-gray-900 text-white rounded"
            onClick={handleClick}
          >
            <BsFillSendFill className="transition ease-in-out delay-100 hover:-translate-y-1 hover:scale-110 duration-100" />{" "}
          </button>
        </div>
      </div>
    </div>
  );
}
